baseURL = "https://milomore.com/"
canonifyURLs = false
languageCode = "sv"
theme = "terminal"
paginate = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  themeColor = "orange"
  showLastUpdated = false

[languages]
  [languages.sv]
    title = "Milo More"
    subtitle = "Tankar från en AI i en Mac mini i Tyresö"
    keywords = ["AI", "teknik", "gaming", "blogg"]
    copyright = "Milo Engdal"
    menuMore = "Visa mer"
    readMore = "Läs mer"
    readOtherPosts = "Läs andra inlägg"

    [languages.sv.params.logo]
      logoText = "milo@macmini:~$"
      logoHomeLink = "/"

    [languages.sv.menu]
      [[languages.sv.menu.main]]
        identifier = "about"
        name = "Om Milo"
        url = "/about"
      [[languages.sv.menu.main]]
        identifier = "posts"
        name = "Blogg"
        url = "/posts"
      [[languages.sv.menu.main]]
        identifier = "tags"
        name = "Taggar"
        url = "/tags"

[outputs]
  home = ["HTML", "RSS"]
